### ISSUE TITLE
Repeatable field doesn't display info on payment history

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-checkout-fields#117]
The repeatable field throws an error on submission:

<img width="908" alt="screen shot 2017-04-03 at 1 34 53 pm" src="https://cloud.githubusercontent.com/assets/36433/24624986/31c1a2dc-1873-11e7-89be-0aa36e942b27.png">

This results in the information not being displayed in the backend, just an empty repeatable field.

**Comment by cklosowski** [comment]
This should be fixed in `issue/119` alongside #119

**Comment by SDavisMedia** [comment]
This only seems to fix the issue when there are at least 2 fields used by the repeat field on checkout. If left as just one field, the field still shows up blank on the purchase record.

**Comment by SDavisMedia** [comment]
This is good to go now. :+1:
